version: '3'
volumes:
  postgres_jano:

services:
  db:
    image: 'postgres:14.4'
    container_name: db-jano
    environment:
      POSTGRES_DB: jano
      POSTGRES_USER: jano
      POSTGRES_PASSWORD: jano
    volumes:
      - 'postgres_jano:/var/lib/postgresql/data'
    ports:
      - "5432:5432"